#!/bin/bash
set -e
cd "$(dirname "$0")"
rm -rf constant/polyMesh 0/polyMesh processor* postProcessing postProcessing_stage log.* 200 400 800
blockMesh | tee log.blockMesh
snappyHexMesh -overwrite | tee log.snappyHexMesh
checkMesh | tee log.checkMesh
foamRun -solver incompressibleFluid | tee log.foamRun
python3 ../../scripts/extract_cd_all.py
